version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install mocha
          command: npm install mocha
      - run:    
          name: install npm dependencies
          command: npm install --save
      - run:
          name: start server
          command: npm start --prefix TDD-Assignment
      - run:
          name: run mocha test
          command: mocha TDD-Assignment/server.test.js
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
workflows:
  build_test:
    jobs:
      - run_tests